# Generated by Django 2.2.1 on 2019-05-16 18:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Please enter a valid name', regex='^([A-Za-z])+$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Please enter a valid name', regex='^([A-Za-z])+$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid email address', regex='^([a-zA-Z0-9_\\.\\-])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$')])),
                ('image', models.ImageField(default='images/defaultUser.png', upload_to='images/user_profile/')),
                ('country', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid name', regex='^([A-Za-z])+$')])),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^01[5|1|2|0][0-9]{8}$')])),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
